=== lachiejames/conversation-assistant/functions/generate_suggestions/schemas/gpt3_completion_response.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": ["choices", "created", "id", "model", "object"],
  "properties": {
    "choices": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "required": ["finish_reason", "index", "logprobs", "text"],
          "properties": {
            "finish_reason": {
              "type": "string"
            },
            "index": {
              "type": "integer"
            },
            "logprobs": {
              "type": "null"
            },
            "text": {
              "type": "string"
            }
          }
        }
      ]
    },
    "created": {
      "type": "integer"
    },
    "id": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "object": {
      "type": "string"
    }
  }
}

=== lachiejames/conversation-assistant/conversation_assistant/test/mock_completion_response.json
{
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "text": "    Bot - I work in the tech industry."
    },
    {
      "finish_reason": "stop",
      "index": 1,
      "logprobs": null,
      "text": "    Bot - I am a computer programmer."
    },
    {
      "finish_reason": "stop",
      "index": 2,
      "logprobs": null,
      "text": "    Bot - I work in the technology industry."
    }
  ],
  "created": 1640685201,
  "id": "cmpl-4K3STZU7XR1csfhQWTvlVD2TVxKDf",
  "model": "davinci-instruct-v3:2021-11-19",
  "object": "text_completion"
}
